---
#
# Group variables for all hosts in the myhosts group
# These variables apply to all servers in the deployment
#

# Deployment control flags
configure_system: false # Set to true to run system configuration tasks
deploy_infrastructure: true
deploy_backup: true
deploy_applications: true

# Docker configuration
docker_base_folder: /docker
docker_proxy_network: "proxy"
docker_proxy_security_network: "proxysec"

# Traefik configuration
docker_traefik_https_endpoint: "web-secure"
docker_traefik_auth_middleware: "proxyauth"
docker_traefik_lan_middleware: "lan-whitelist@file"

# MQTT configuration
mosquitto_mqtt_port: "1883/tcp"
mosquitto_mqttsecure_port: "8883/tcp"

# Docker image versions - centralized version management
docker_images:
  # Infrastructure services
  traefik: "traefik:v3"
  authentik:
    server: "ghcr.io/goauthentik/server:2025.6"
    ldap: "ghcr.io/goauthentik/ldap:2025.6"
  postgres: "docker.io/library/postgres:16-alpine"
  redis: "docker.io/library/redis:alpine"

  # Security services
  crowdsec: "crowdsecurity/crowdsec:latest-debian"

  # Media services
  jellyfin: "jellyfin/jellyfin:latest"
  jellyseer: "fallenbagel/jellyseerr:latest"
  jellyplex_watched: "luigi311/jellyplex-watched:latest"
  gluetun: "qmcgaw/gluetun:v3.40.0"

  # Monitoring services
  uptime_kuma: "louislam/uptime-kuma:1"
  socket_proxy: "wollomatic/socket-proxy:1"
  wud: "getwud/wud:latest"

  # Dashboard services
  homarr: "ghcr.io/homarr-labs/homarr:latest"

  # Backup services
  borgwarehouse: "borgwarehouse/borgwarehouse:latest"

# Legacy variables for backward compatibility
authentik_docker_tag: "2025.6"

# System packages required for all deployments
base_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - python3-yaml

# NTP servers for time synchronization
ntp_servers:
  - 0.de.pool.ntp.org
  - 1.de.pool.ntp.org
  - 2.de.pool.ntp.org
  - 3.de.pool.ntp.org
