---
#
# Central Server Deployment Playbook
# This playbook deploys a complete Docker-based service stack including:
# - Reverse proxy (Traefik)
# - Authentication (Authentik)
# - Security (CrowdSec)
# - Media services (Jellyfin, Jellyseer)
# - Backup (Borg, BorgWarehouse)
# - Monitoring (UptimeKuma, WUD)
#
- name: Deploy Central Server Infrastructure
  hosts: myhosts
  become: true
  gather_facts: true

  # Global variables for the deployment
  vars:
    # Dynamic Traefik entrypoints (host-specific)
    traefik_entrypoints:
      borgwarehousessh: "{{ borgwarehouse_ssh_port }}"
      mqtt: "{{ mosquitto_mqtt_port }}"
      mqttsecure: "{{ mosquitto_mqttsecure_port }}"

  # Pre-deployment tasks
  pre_tasks:
    - name: Install base system packages
      ansible.builtin.apt:
        name: "{{ base_packages }}"
        state: present
        update_cache: true
      tags:
        - system-configuration
        - packages

    - name: Create Docker data directory
      ansible.builtin.file:
        path: "{{ docker_base_folder }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      tags:
        - system-configuration
        - directories

    - name: Verify system readiness
      ansible.builtin.debug:
        msg: "System is ready for service deployment on {{ inventory_hostname }}"
      tags:
        - system-configuration

  # System configuration roles
  tasks:
    - name: Configure system-level components
      tags:
        - system-configuration
      when: configure_system | default(false)
      block:
        - name: Apply unattended upgrades configuration
          ansible.builtin.include_role:
            name: hifis.toolkit.unattended_upgrades
          tags:
            - unattended-upgrades

        - name: Configure time synchronization
          ansible.builtin.include_role:
            name: idiv_biodiversity.systemd.systemd_timesyncd
          vars:
            systemd_timesyncd_ntp_servers: "{{ ntp_servers }}"
            systemd_timesyncd_remove_legacy_packages: true
          tags:
            - time-sync

        - name: Install and configure Docker
          ansible.builtin.include_role:
            name: geerlingguy.docker
          tags:
            - docker

        - name: Configure networking
          ansible.builtin.include_role:
            name: networking
          tags:
            - networking

        - name: Configure dynamic DNS
          ansible.builtin.include_role:
            name: mivek.inadyn
          tags:
            - dyndns

    - name: Deploy infrastructure services
      tags:
        - infrastructure
        - services
      block:
        - name: Deploy Traefik reverse proxy
          ansible.builtin.include_role:
            name: traefik
          tags:
            - traefik
            - proxy

        - name: Deploy Authentik authentication
          ansible.builtin.include_role:
            name: authentik
          tags:
            - authentik
            - authentication

        - name: Deploy CrowdSec security
          ansible.builtin.include_role:
            name: crowdsec
          tags:
            - crowdsec
            - security

    - name: Deploy backup services
      tags:
        - backup
        - services
      block:
        - name: Deploy BorgWarehouse backup server
          ansible.builtin.include_role:
            name: borgwarehouse
          tags:
            - borgwarehouse

        - name: Configure Borg backup client
          ansible.builtin.include_role:
            name: borg
          tags:
            - borg

    - name: Deploy application services
      tags:
        - applications
        - services
      block:
        - name: Deploy media services stack
          ansible.builtin.include_role:
            name: media
          tags:
            - media
            - jellyfin
            - jellyseer
            - qbittorrent
            - gluetun

        - name: Deploy paperless services stack
          ansible.builtin.include_role:
            name: paperless
          tags:
            - paperless

        - name: Deploy monitoring services
          tags:
            - monitoring
          block:
            - name: Deploy UptimeKuma monitoring
              ansible.builtin.include_role:
                name: uptimekuma
              tags:
                - uptimekuma

            - name: Deploy WUD update detector
              ansible.builtin.include_role:
                name: wud
              tags:
                - wud

  # Post-deployment tasks
  post_tasks:
    - name: Verify service deployment
      ansible.builtin.debug:
        msg: "All services have been deployed successfully on {{ inventory_hostname }}"
      tags:
        - verification

    - name: Display service URLs
      ansible.builtin.debug:
        msg: |
          Services are available at:
          - Traefik Dashboard: https://{{ ansible_host }}/dashboard/
          - Authentik: https://{{ ansible_host }}/auth/
          - UptimeKuma: https://{{ ansible_host }}/uptime/
          - Media Services: https://{{ ansible_host }}/media/
      tags:
        - verification
        - info
