---
- name: Central Setup
  hosts: myhosts
  become: true
  vars:
    docker_base_folder: /docker
    docker_proxy_network: "proxy"
    docker_proxy_security_network: "proxysec"
    docker_traefik_https_endpoint: "web-secure"
    docker_traefik_auth_middleware: "proxyauth"
    docker_traefik_lan_middleware: "lan-whitelist@file"
    mosquitto_mqtt_port: "1883/tcp"
    mosquitto_mqttsecure_port: "8883/tcp"
    authentik_docker_tag: "2025.6"
    docker_traefik_entrypoints:
      borgwarehousessh: "{{ borgwarehouse_ssh_port }}"
      mqtt: "{{ mosquitto_mqtt_port }}"
      mqttsecure: "{{ mosquitto_mqttsecure_port }}"

  roles:
    - role: hifis.toolkit.unattended_upgrades
      tags:
        - never
        - system-configuration
    - role: idiv_biodiversity.systemd.systemd_timesyncd
      tags:
        - never
        - system-configuration
      vars:
        systemd_timesyncd_ntp_servers:
          - 0.de.pool.ntp.org
          - 1.de.pool.ntp.org
          - 2.de.pool.ntp.org
          - 3.de.pool.ntp.org
        systemd_timesyncd_remove_legacy_packages: true
    - role: geerlingguy.docker
      tags:
        - never
        - system-configuration
    - role: networking
      tags:
        - never
        - networking
        - system-configuration
    - role: mivek.inadyn
      tags:
        - never
        - inadyn
        - networking
        - system-configuration
    - role: traefik
      tags:
        - services
        - traefik
    - role: authentik
      tags:
        - services
        - authentik
    - role: crowdsec
      tags:
        - services
        - crowdsec
    - role: borgwarehouse
      tags:
        - services
        - borgwarehouse
        - backup
    - role: borg
      tags:
        - services
        - borg
        - backup
    - role: media
      tags:
        - services
        - media
    - role: uptimekuma
      tags:
        - services
        - uptimekuma
    - role: wud
      tags:
        - services
        - wud
  pre_tasks:
    - name: Install base packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-yaml
        state: present
      tags:
        - never
        - system-configuration

    - name: Create docker data folder
      ansible.builtin.file:
        path: /docker/
        state: directory
        owner: root
        group: root
        mode: "0755"
      tags:
        - never
        - system-configuration
