---
- name: Central Setup
  hosts: myhosts
  become: true
  vars:
    docker_base_folder: /docker
    docker_proxy_network: "proxy"
    docker_proxy_security_network: "proxysec"
    docker_traefik_proxy_network_addresses:
      ipv4_address: "172.18.0.2"
      ipv6_address: "fd3c:3065:18::2"
    docker_traefik_proxy_security_network_addresses:
      ipv4_address: "172.19.0.2"
      ipv6_address: "fd3c:3065:19::2"
    docker_traefik_https_endpoint: "web-secure"
    docker_traefik_auth_middleware: "proxyauth"
    docker_traefik_lan_middleware: "lan-whitelist@file"
    mosquitto_mqtt_port: "1883/tcp"
    mosquitto_mqttsecure_port: "8883/tcp"
    docker_traefik_lan_ip_allowlist:
      # Docker internal ranges
      - "127.0.0.1/32"
      - "172.0.0.0/8"
      - "fd3c:3065:18::/64"
      - "fd3c:3065:19::/64"
      - "fd83:b67c:046c::/48"
      # LAN ranges
      - "10.138.0.0/16"
      - "fd4f:8843:b4e6::/48"
      - "fe80::0/64"
      # V-Server
      - "10.0.0.2/32"
      - "fdbd:2a35:2f10::2/128"
    authentik_docker_tag: "2025.6"
    borgwarehouse_ssh_port: "11022/tcp"
    borg_backup_repository: "ssh://borgwarehouse@backup.msch.cc:11022/./ca807104"
    docker_traefik_entrypoints:
      borgwarehousessh: "{{ borgwarehouse_ssh_port }}"
      mqtt: "{{ mosquitto_mqtt_port }}"
      mqttsecure: "{{ mosquitto_mqttsecure_port }}"

  roles:
    - role: hifis.toolkit.unattended_upgrades
      tags:
        - never
        - system-configuration
    - role: idiv_biodiversity.systemd.systemd_timesyncd
      tags:
        - never
        - system-configuration
      vars:
        systemd_timesyncd_ntp_servers:
          - 0.de.pool.ntp.org
          - 1.de.pool.ntp.org
          - 2.de.pool.ntp.org
          - 3.de.pool.ntp.org
        systemd_timesyncd_remove_legacy_packages: true
    - role: geerlingguy.docker
      tags:
        - never
        - system-configuration
    - role: networking
      tags:
        - never
        - networking
        - system-configuration
    - role: mivek.inadyn
      tags:
        - never
        - inadyn
        - networking
        - system-configuration
    - role: traefik
      tags:
        - services
        - traefik
    - role: authentik
      tags:
        - services
        - authentik
    - role: crowdsec
      tags:
        - services
        - crowdsec
    - role: borgwarehouse
      tags:
        - services
        - borgwarehouse
        - backup
    - role: borg
      tags:
        - services
        - borg
        - backup
    - role: media
      tags:
        - services
        - media
    - role: homarr
      tags:
        - services
        - homarr
  pre_tasks:
    - name: Install base packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-yaml
        state: present
      tags:
        - never
        - system-configuration

    - name: Create docker data folder
      ansible.builtin.file:
        path: /docker/
        state: directory
        owner: root
        group: root
        mode: "0755"
      tags:
        - never
        - system-configuration
