---
- name: Central Setup
  hosts: myhosts
  become: true
  vars:
    docker_base_folder: /docker
    docker_proxy_network: "proxy"
    docker_proxy_security_network: "proxysec"
    docker_traefik_https_endpoint: "web-secure"
    docker_traefik_auth_middleware: "proxyauth"
    docker_traefik_lan_middleware: "lan-whitelist@file"
    authentik_docker_tag: "2025.2"
    borgwarehouse_ssh_port: 11022
    mosquitto_mqtt_port: 1883
    mosquitto_mqttsecure_port: 8883
    borg_backup_repository: "ssh://borgwarehouse@backup.msch.cc:11022/./ca807104"
    traefik_additional_entrypoints:
      borgwarehousessh:
        address: ":{{ borgwarehouse_ssh_port }}"
      mqtt:
        address: ":{{ mosquitto_mqtt_port }}"
      mqttsecure:
        address: ":{{ mosquitto_mqttsecure_port }}"

  roles:
    - role: hifis.toolkit.unattended_upgrades
      tags:
        - never
        - system-configuration
    - role: idiv_biodiversity.systemd.systemd_timesyncd
      tags:
        - never
        - system-configuration
      vars:
        systemd_timesyncd_ntp_servers:
          - 0.de.pool.ntp.org
          - 1.de.pool.ntp.org
          - 2.de.pool.ntp.org
          - 3.de.pool.ntp.org
        systemd_timesyncd_remove_legacy_packages: true
    - role: geerlingguy.docker
      tags:
        - never
        - system-configuration
    - role: networking
      tags:
        - never
        - networking
        - system-configuration
    - role: mivek.inadyn
      tags:
        - never
        - inadyn
        - networking
        - system-configuration
    - role: authentik
      tags:
        - services
        - authentik
    - role: crowdsec
      tags:
        - services
        - crowdsec
    - role: traefik
      tags:
        - services
        - traefik
    - role: borgwarehouse
      tags:
        - services
        - borgwarehouse
        - backup
    - role: borg
      tags:
        - services
        - borg
        - backup
    - role: jellyfin
      tags:
        - services
        - jellyfin
    # - role: portainer
    #  tags:
    #    - services
    #    - portainer
  pre_tasks:
    - name: Install base packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-yaml
        state: present
      tags:
        - never
        - system-configuration

    - name: Create docker data folder
      ansible.builtin.file:
        path: /docker/
        state: directory
        owner: root
        group: root
        mode: "0755"
      tags:
        - never
        - system-configuration
