---
roles:
  - geerlingguy.docker
  - aruhier.systemd_networkd
  - mivek.inadyn
  - singleplatform-eng.users

collections:
  - community.general
  - community.docker
  - idiv_biodiversity.systemd
  - hifis.toolkit
