---
roles:
  - geerlingguy.docker
  - aruhier.systemd_networkd
  - src: git+https://github.com/merlinschumacher/ansible-role-inadyn
    name: mivek.inadyn

collections:
  - community.general
  - community.docker
  - idiv_biodiversity.systemd
  - hifis.toolkit
