---
external_ipv4: 10.138.1.10
external_ipv6: "fe80::7285:c2ff:fe93:31b2"
traefik_cf_email: merlin.schumacher@gmail.com
networking_wireguard_peer:
    publickey: 8Co5YSeDH7355ZcdkKiNqBg8Ejhe+ZzF7PY9cByHF08=
    allowedips: "10.0.0.1/32, fdbd:2a35:2f10::1,128"
    endpoint: "mail.merlinschumacher.de:51871"
mailserver_hostname: mail.merlinschumacher.de
mailserver_port: 465
mailserver_username: notifications@merlinschumacher.de
borgwarehouse_repo_folder: "/srv/media3/backup/"