---
external_ipv4: 10.138.1.10
external_ipv6: "fe80::7285:c2ff:fe93:31b2"
traefik_cf_email: merlin.schumacher@gmail.com
networking_wireguard_peer:
  publickey: 8Co5YSeDH7355ZcdkKiNqBg8Ejhe+ZzF7PY9cByHF08=
  allowedips: "10.0.0.1/32, fdbd:2a35:2f10::1,128"
  endpoint: "mail.merlinschumacher.de:51871"
mailserver_hostname: mail.merlinschumacher.de
mailserver_port: 465
mailserver_username: notifications@merlinschumacher.de
borgwarehouse_repo_folder: "/srv/media3/backup/"
cf_dyndns_hostname: msch.cc
cf_dyndns_zoneid: msch.cc
cf_dyndns_hostname2: home.merlinschumacher.de
cf_dyndns_zoneid2: merlinschumacher.de
inadyn_allow_ipv6: true
inadyn_providers:
  - name: cloudflare
    index: 1
    username: "{{ cf_dyndns_zoneid }}"
    password: "{{ cf_dyndns_token }}"
    hostname: "{{ cf_dyndns_hostname }}"
    checkip_server: "1.1.1.1"
    checkip_path: "/cdn-cgi/trace"
  - name: cloudflare
    index: 2
    username: "{{ cf_dyndns_zoneid }}"
    password: "{{ cf_dyndns_token }}"
    hostname: "{{ cf_dyndns_hostname }}"
    checkip_server: "dns64.cloudflare-dns.com"
    checkip_path: "/cdn-cgi/trace"
  - name: cloudflare
    index: 3
    username: "{{ cf_dyndns_zoneid2 }}"
    password: "{{ cf_dyndns_token }}"
    hostname: "{{ cf_dyndns_hostname2 }}"
    checkip_server: "1.1.1.1"
    checkip_path: "/cdn-cgi/trace"
  - name: cloudflare
    index: 4
    username: "{{ cf_dyndns_zoneid2 }}"
    password: "{{ cf_dyndns_token }}"
    hostname: "{{ cf_dyndns_hostname2 }}"
    checkip_server: "dns64.cloudflare-dns.com"
    checkip_path: "/cdn-cgi/trace"
docker_traefik_proxy_network_addresses:
  ipv4_address: "172.18.128.2"
  ipv6_address: "fd3c:3065:18::1:2"
docker_traefik_proxy_security_network_addresses:
  ipv4_address: "172.19.128.2"
  ipv6_address: "fd3c:3065:19::1:2"
docker_traefik_lan_ip_allowlist:
  # Docker internal ranges
  - "127.0.0.1/32"
  - "172.0.0.0/8"
  - "fd3c:3065:18::/64"
  - "fd3c:3065:19::/64"
  - "fd83:b67c:046c::/48"
  # LAN ranges
  - "10.138.0.0/16"
  - "fd4f:8843:b4e6::/48"
  - "fe80::0/64"
  # V-Server
  - "10.0.0.2/32"
  - "fdbd:2a35:2f10::2/128"
borgwarehouse_ssh_port: "11022/tcp"
borg_backup_repository: "ssh://borgwarehouse@backup.msch.cc:11022/./ca807104"
