---
galaxy_info:
  role_name: traefik
  description: Deploy Traefik reverse proxy with Docker Compose and automatic HTTPS
  author: merlinschumacher
  company: Personal
  license: MIT
  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - docker
    - proxy
    - traefik
    - reverseproxy
    - https
    - letsencrypt

allow_duplicates: false
