---
- name: Create gluetun config folder
  ansible.builtin.file:
    name: "{{ media_gluetun_base_folder }}"
    state: directory
    mode: "0700"
    force: false

- name: Create gluetun compose files from template
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ media_base_folder }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    mode: "0640"
  with_items:
    - "gluetun.yaml.j2"
    - "gluetun.env.j2"
  notify:
    - media-recreate
