---
- name: Create jellyfin compose file from template
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ media_base_folder }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    mode: "0640"
  with_items:
    - "jellyplex-watched.yaml.j2"
    - "jellyplex-watched.env.j2"
  notify:
    - media-recreate
