---
- name: Create jellyseer config folder
  ansible.builtin.file:
    name: "{{ media_jellyseer_base_folder }}/config"
    state: directory
    owner: 1000
    group: 1000
    mode: "0700"
    force: false

- name: Create jellyseer compose files from template
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ media_base_folder }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    mode: "0640"
  with_items:
    - "jellyseer.yaml.j2"
    - "jellyseer.env.j2"
  notify:
    - media-recreate
