---
- name: Get user id for group
  ansible.builtin.getent:
    database: group

- name: Get id for docker group
  ansible.builtin.set_fact:
    docker_group: "{{ ansible_facts.getent_group['docker'][1] }}"

- name: Create uptimekuma user
  ansible.builtin.include_role:
    name: singleplatform-eng.users
  vars:
    users:
      - username: "{{ uptimekuma_user }}"
        users_create_per_user_group: true
        shell: /bin/false
        create_home: false
        system: true

- name: Create  uptimekuma base folder
  ansible.builtin.file:
    name: "{{ uptimekuma_base_folder }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0750"

- name: Create uptimekuma data folder
  ansible.builtin.file:
    name: "{{ uptimekuma_base_folder }}/data/uptimekuma"
    state: directory
    owner: "uptimekuma"
    group: "uptimekuma"
    mode: "0750"

- name: Create uptimekuma files from templates
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ uptimekuma_base_folder }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    mode: "0640"
  with_items:
    - "compose.yaml.j2"
  notify:
    - uptimekuma-recreate
