---
- name: Create borgwarehouse container
  community.docker.docker_compose_v2:
    project_src: "{{ borgwarehouse_base_folder }}"
    state: present
    recreate: "always"
  listen: borgwarehouse-recreate
