---
- name: Create Traefik acme folder
  ansible.builtin.file:
    name: "{{ traefik_base_folder }}/data/acme"
    state: directory
    owner: root
    group: root
    mode: "0700"
    force: false

- name: Create traefik compose file from template
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ traefik_base_folder }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    mode: "0640"
  with_items:
    - "compose.yaml.j2"
    - "traefik.env.j2"
  notify:
    - traefik-recreate

- name: Create traefik config files from template
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ traefik_base_folder }}/data/{{ item | basename | regex_replace('\\.j2$', '') }}"
    mode: "0640"
  with_items:
    - "traefik.yaml.j2"
    - "dynamic.yaml.j2"
  notify:
    - traefik-recreate
