---
# Input validation for Traefik role
- name: Validate required variables
  ansible.builtin.assert:
    that:
      - docker_base_folder is defined
      - docker_base_folder | length > 0
      - docker_proxy_network is defined
      - docker_proxy_security_network is defined
      - traefik_proxy_network_addresses is defined
      - traefik_proxy_security_network_addresses is defined
    fail_msg: "Required Traefik variables are missing or invalid"
    quiet: true

- name: Validate Docker base directory exists
  ansible.builtin.stat:
    path: "{{ docker_base_folder }}"
  register: docker_base_stat
  failed_when: not docker_base_stat.stat.exists or not docker_base_stat.stat.isdir

- name: Validate Traefik configuration directories
  ansible.builtin.stat:
    path: "{{ traefik_base_folder }}"
  register: traefik_base_stat

- name: Validate network addresses format
  ansible.builtin.assert:
    that:
      - traefik_proxy_network_addresses.ipv4_address is match("^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$")
    fail_msg: "Invalid IPv4 address format in network configuration"
    quiet: true
  when: traefik_proxy_network_addresses.ipv4_address is defined
